"use client";

import { useState } from "react";

interface QrCodeProps {
  /** The URL to encode. */
  value: string;
  size?: number;
}

/**
 * Renders a scannable QR code for the install URL (desktop "scan to install"
 * flow). The QR image is generated by a public QR endpoint at render time; the
 * encoded URL is always shown as readable text below so the feature degrades
 * gracefully if the image cannot load (offline, blocked, etc.).
 *
 * NOTE: relies on a third-party QR image service. Vendoring an offline QR
 * generator is tracked as a follow-up (see docs/MOBILE.md).
 */
export function QrCode({ value, size = 200 }: QrCodeProps) {
  const [failed, setFailed] = useState(false);
  const src = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=0&data=${encodeURIComponent(
    value
  )}`;

  return (
    <div className="flex flex-col items-center gap-3">
      <div
        className="rounded-xl bg-white p-3 border border-border-default flex items-center justify-center"
        style={{ width: size + 24, height: size + 24 }}
      >
        {failed ? (
          <span className="text-xs text-text-tertiary text-center px-2">
            QR unavailable — open the link below
          </span>
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={src}
            width={size}
            height={size}
            alt={`QR code linking to ${value}`}
            onError={() => setFailed(true)}
          />
        )}
      </div>
      <a
        href={value}
        className="text-xs font-mono text-accent hover:underline break-all text-center max-w-[240px]"
      >
        {value.replace(/^https?:\/\//, "")}
      </a>
    </div>
  );
}
